---
title: "Mini-benchmark"
author: "Alejandro Efraín Marín Peralta"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float:
      toc_collapsed: true
    toc_depth: 3
    number_sections: true
    theme: lumen
  pdf_document:
    toc: true
    toc_depth: '3'
---


# Title


```{r libraries, message=FALSE, warning=FALSE}
library(tidyverse)
library(arrow)
library(magrittr)
library(fs)
library(ggbeeswarm)
library(UpSetR)
library(arrow)
library(pheatmap)
library(viridis)

set.seed(0)
setwd("~/Documents/EMBL_UniHD/mini-benchmark")


org_cols <- c(
  Ecoli    = "#007B53",
  Hsapiens = "#193F90"
)
```



```{r functions}
# Auxiliary functions

## Computes Jaccard Index
jaccard <- function(x, y) {
  length(intersect(x, y)) / length(union(x, y))
}


## Commputes jaccard index pairwise of list
jpw <- function(x) {
  n <- names(x)
  ## Expands pairwise
  expand_grid(
    names1 = n,
    names2 = n,
  ) %>% 
    ## Maps the function fer columns
    mutate(
      index = map2_dbl(x[names1], x[names2], jaccard)
    ) %>% 
    ## Comes back to squared datafra,e
    pivot_wider(
      names_from = names2,
      values_from = index
    ) %>%
    column_to_rownames("names1") 
}


## Get protein groups from parquet DIA-NN output
pg <- function(x) {
  x %>% 
    collect() %>% 
    pull(Protein.Group) %>% 
    unique()
}

## Get proteins from parquet DIA-NN output
proteins <- function(x) {
  x %>% 
    collect() %>% 
    pull(Protein.Ids) %>% 
    unique()
}

## Get peptides from parquet DIA-NN output
peptides <- function(x) {
  x %>% 
    collect() %>% 
    pull(Stripped.Sequence) %>% 
    unique()
}

```





## Computing metrics


```{r comp_functions}
# Auxiliary functions to convert units

## Function to convert units to MB
get_MB <- function(x) {
  ## Trim whitespace
  x %<>% as.character() %>% 
    trimws()
  
  ## Gets numeric value
  val <- str_extract(x, "[0-9]+(\\.[0-9]+)?") %>% 
    as.numeric()
  
  ## Gets unit
  unit <- str_extract(x, "[A-Za-z]+") %>% 
    toupper()
  
  ## Gets MB
  value_mb = case_when(
    unit %in% c("KB", "K")  ~ val / 1024,
    unit %in% c("MB", "M")  ~ val,
    unit %in% c("GB", "G") ~ val * 1024,
    unit %in% c("TB", "T") ~ val * 1024 * 1024,
    TRUE ~ NA_real_
  )
  
  ## Return megabytes
  return(value_mb)
}


## Function to get time information into seconds
get_seconds <- function(x) {
  x %<>% as.character()
  
  ## Gets time with regex
  h <- x %>% 
    str_extract(., "\\d+(?=h)") %>% 
    as.numeric()
  m <- x %>% 
    str_extract(., "\\d+(?=m)") %>% 
    as.numeric()
  ## Regex to allow decimal seconds
  s <- x %>% 
    str_extract(., "\\d+(?:\\.\\d+)?(?=s)") %>% 
    as.numeric()
  
  # Replace NAa with 0
  h[is.na(h)] <- 0
  m[is.na(m)] <- 0
  s[is.na(s)] <- 0
  
  ## Return seconds
  return(h * 3600 + m * 60 + s)
}
```


Gets metadata from server after running
`ls -lh */*/data/*raw | tr -s ' ' '\t' > files_list.tsv` and then secure copying
it to the local root.

```{r raw_info, message=FALSE}
raw_info <- read_tsv("./files_list.tsv",
                     col_names = FALSE)

head(raw_info)


## Keeps just the necessary information
raw_info %<>% select(c("X5", "X9")) %>% 
  purrr::set_names(c("size", "fullname"))

## Mutates the tibble
raw_info %<>% mutate(size_MB = get_MB(size)) %>% 
  separate(
    fullname,
    into = c("instrument", "organism", "subfolder", "file_name"),
    sep = "/"
  )

head(raw_info)



ggplot(raw_info, aes(y = size_MB / 1024, x = '')) +
  geom_beeswarm() +
  theme_minimal() +
  ylim(0, 12.5) +
  labs(
    x = "",
    y = "Raw file size (GB)"
  ) +
  ggtitle("All sizes")



ggplot(raw_info, aes(x = instrument, y = size_MB / 1024, colour = organism)) +
  geom_beeswarm(size = 2, alpha = 0.7) +
  scale_x_discrete(limits = c("FusionLumos", "Exploris480", "Astral")) +
  scale_colour_manual(
    name = "Organism",
    values = org_cols
  ) +
  theme_minimal() +
  ylim(0, 12.5) +
  labs(
    x = "Mass Spectrometer",
    y = "Raw file size (GB)"
  ) +
  ggtitle("Size of raw files")



ggplot(raw_info, aes(x = organism, y = size_MB / 1024, colour =  instrument)) +
  geom_beeswarm(size = 2, alpha = 0.9) +
  scale_x_discrete(limits = c("Ecoli", "Hsapiens")) +
  theme_minimal() +
  ylim(0, 12.5) +
  labs(
    x = "Organism",
    y = "Raw file size (GB)"
  ) +
  ggtitle("Size of raw files")

```


```{r summarize_raw}
## Collapse into average size of raw files
raw_summary <- raw_info %>%
  group_by(instrument, organism) %>%
  summarise(
    avg_raw_size = mean(size_MB, na.rm = TRUE),
    ## Cleans unnecessary metadata
    .groups  = "drop"
  ) %>% 
  ## Converts back to GB
  mutate(avg_raw_size = avg_raw_size / 1024)



```


```{r fasta_info}
fasta_info <- read_tsv("./fasta_list.tsv",
                       col_names = FALSE)


fasta_info

## Filter out unnecessary columns
fasta_info %<>% select(c("X5", "X9")) %>% 
  purrr::set_names(c("size", "fullname")) %>% 
  mutate(size_MB = get_MB(size)) %>% 
  ## Get organism name with regex
  mutate(organism = str_extract(fullname, "(?<=/)[^/_]+(?=_)"))

```



Get times after doing `grep -m1 'duration: <strong>' */*/*/nf_report.html > runtimes.txt`

```{r runtimes, message=FALSE}
runtimes <- read_delim("runtimes.txt",
                       delim =  "          ", ## By some reason grep created 10 whitespaces
                       col_names = FALSE) %>% 
  set_names(c("run", "string")) %>% 
  mutate(time = get_seconds(string) / 60,
         instrument = word(run, 1, sep = "/"),
         organism = word(run, 2, sep = "/"),
         profile = word(run, 3, sep = "/")) %>% 
  select(!run) %>% 
  select(!string)



runtimes %>% 
  filter(!str_detect(profile, "1\\.9\\.1")) %>% 
  ggplot() +
  geom_beeswarm(aes(y = time / 60, x = instrument, colour = organism),
                size = 2,
                alpha = 0.8,
                ) +
  scale_colour_manual(
    name = "Organism",
    values = org_cols
  ) +
  geom_boxplot(aes(y = time / 60, x = instrument),
               width = .25, alpha = 0, 
               outlier.shape = NA) +
  scale_x_discrete(limits = c("FusionLumos", "Exploris480", "Astral")) +
  theme_minimal() +
  labs(
    x =  "Mass Spectrometer",
    y = "Total runtime (h)"
  )



runtimes %>% 
  filter(!str_detect(profile, "1\\.9\\.1")) %>% 
  ggplot() +
  geom_beeswarm(aes(y = time / 60, x = organism, colour = instrument),
                size = 2,
                alpha = 0.9,
  ) +
  geom_boxplot(aes(y = time / 60, x = organism),
               width = .25, alpha = 0, 
               outlier.shape = NA) +
  scale_x_discrete(limits = c("Ecoli", "Hsapiens")) +
  theme_minimal() +
  labs(
    x =  "Organism",
    y = "Total runtime (h)"
  )



size_time <- left_join(runtimes, raw_summary,
                       by = c("instrument", "organism"))



size_time %>% 
  filter(!str_detect(profile, "1\\.9\\.1")) %>% 
  ggplot(aes(x = avg_raw_size, y = time /60 ,
                        colour = organism,
                        shape = instrument)) +
  geom_point(size = 2, alpha = 0.8) +
  scale_colour_manual(
    name = "Organism",
    values = org_cols
  ) +
  theme_minimal() +
  labs(
    x = "Average raw file size (GB)",
    y = "Total runtime (h)" 
  )


size_time %>% 
  filter(!str_detect(profile, "1\\.9\\.1")) %>% 
  ggplot(aes(x = avg_raw_size, y = time /60 ,
                        colour = instrument,
                        shape = organism)) +
  geom_point(size = 2, alpha = 0.8) +
  theme_minimal() +
  labs(
    x = "Average raw file size (GB)",
    y = "Total runtime (h)" 
  )


size_time %>%
  filter(!str_detect(profile, "1\\.9\\.1")) %>% 
  filter(instrument == "Astral") %>% 
  ggplot(aes(x = avg_raw_size, y = time /60 ,
             colour = organism)) +
  geom_point(size = 2, alpha = 0.8) +
  scale_colour_manual(
    name = "Organism",
    values = org_cols
  ) +
  theme_minimal() +
  labs(
    x = "Average raw file size (GB)",
    y = "Total runtime (h)" 
  ) +
  ggtitle("Astral runs")



size_time %>%
  filter(!str_detect(profile, "1\\.9\\.1")) %>% 
  filter(instrument == "Exploris480") %>% 
  ggplot(aes(x = avg_raw_size, y = time /60 ,
             colour = organism)) +
  geom_point(size = 2, alpha = 0.8) +
  scale_colour_manual(
    name = "Organism",
    values = org_cols
  ) +
  theme_minimal() +
  labs(
    x = "Average raw file size (GB)",
    y = "Total runtime (h)" 
  ) +
  ggtitle("Exploris480 runs")



size_time %>%
  filter(!str_detect(profile, "1\\.9\\.1")) %>% 
  filter(instrument == "FusionLumos") %>% 
  ggplot(aes(x = avg_raw_size, y = time /60 ,
             colour = organism)) +
  geom_point(size = 2, alpha = 0.8) +
  scale_colour_manual(
    name = "Organism",
    values = org_cols
  ) +
  theme_minimal() +
  labs(
    x = "Average raw file size (GB)",
    y = "Total runtime (h)" 
  ) +
  ggtitle("FusionLumos runs")


size_time %>% 
  filter(!str_detect(profile, "1\\.9\\.1")) %>% 
  ggplot(aes(x = avg_raw_size, y = time /60 ,
                        colour = organism, 
                        shape = instrument)) +
  geom_point(size = 3, alpha = 0.8) +
  scale_colour_manual(
    name = "Organism",
    values = org_cols
  ) +
  theme_minimal() +
  labs(
    x = "Average raw file size (GB)",
    y = "Total runtime (h)" 
  )



```




```{r read_traces, message=FALSE}
## Gets names of the traces TSVs
traces_files <- dir_ls(
  path = ".",
  recurse = TRUE,
  glob = "*nf_trace.tsv"
)

## Reads all the trace files
traces_list <- traces_files %>% 
  purrr::set_names() %>% 
  map(read_tsv)
```



```{r warning=FALSE}
## Using map because it is a list of tibbles
traces_list %<>% map(
  ~ mutate(
    .x,
    
    ### Convert time metrics to seconds
    duration_seconds = get_seconds(duration),
    realtime_seconds = get_seconds(realtime),
    
    ### Convert memory metrics to MB
    peak_rss_MB = get_MB(peak_rss),
    peak_vmem_MB = get_MB(peak_vmem),
    rchar_MB = get_MB(rchar),
    wchar_MB = get_MB(wchar),
    
    ### Get CPU percentage
    cpu_percentage = .x %>% 
      pluck("%cpu") %>% 
      str_remove("%") %>% 
      as.numeric()
  )
)
  

## Adds metadata from the tibble name as column
## Use imap() instead if map2() for simplicity
traces_list %<>% imap(~ .x %>% 
                        mutate(
                          instrument = word(.y, 1, sep = "/"),
                          organism = word(.y, 2, sep = "/"),
                          profile = word(.y, 3, sep = "/")
                        ))


traces_list[1] %>% str()
```


summarize everything


```{r traces_times}
## Summarize total times per <instrument/organism/profile>
traces_times <- imap_dfr(traces_list, ~ {
  # split the list‐name (.y) into components
  comb <- str_split(.y, "/", simplify = TRUE)
  tibble(
    instrument = comb[1],
    organism = comb[2],
    profile = comb[3],
    ## Also convert to minutes
    total_duration_min = sum(.x$duration_seconds, na.rm = TRUE) %>% { . / 60 },
    total_realtime_min = sum(.x$realtime_seconds, na.rm = TRUE) %>% { . / 60 }
  )
})
```



## Biological metrics



```{r read_parquets}
parquet_files <- dir_ls(
  path = ".",
  recurse = TRUE,
  glob = "*report.parquet"
)

## Reads all the trace files
parquet_list <- parquet_files %>% 
  purrr::set_names() %>% 
  map(open_dataset, format = "parquet")

```



```{r parquets}
pg_list <- parquet_list %>% 
  map(pg)



proteins_list <- parquet_list %>% 
  map(proteins)



peeptides_list <- parquet_list %>% 
  map(peptides)


```




```{r pg_ecoli}
pg_ecoli <- pg_list %>% 
  { .[str_detect(names(.), "Ecoli")] }




pg_ecoli_astral <- pg_ecoli %>% 
  { .[str_detect(names(.), "Astral")] } %>% 
  set_names( word(names(.), 3, sep = "/") )

pg_ecoli_astral %>% 
  jpw() %>% 
  as.matrix() %>% 
  pheatmap(
    cluster_rows       = TRUE,   # or TRUE if you want clustering
    cluster_cols       = TRUE,
    border_color       = NA,
    color              = viridis(100),
    na_col             = "grey90",
    main               = "Astral E coli | Pairwise Index",
    angle_col          = 45,
    fontsize_row       = 10,
    fontsize_col       = 10,
    cellwidth          = 30,
    cellheight         = 30
  )


pg_ecoli_astral %>% 
  fromList() %>% 
  upset(nsets = ncol(.),
        order.by = "freq",
        decreasing = TRUE,
        nintersects = 10)





pg_ecoli_exploris <- pg_ecoli %>% 
  { .[str_detect(names(.), "Exploris480")] } %>% 
  set_names( word(names(.), 3, sep = "/") )


pg_ecoli_exploris %>% 
  jpw() %>% 
  as.matrix() %>% 
  pheatmap(
    cluster_rows       = TRUE,   # or TRUE if you want clustering
    cluster_cols       = TRUE,
    border_color       = NA,
    color              = viridis(100),
    na_col             = "grey90",
    main               = "Exploris480 E coli | Pairwise Jaccard",
    angle_col          = 45,
    fontsize_row       = 10,
    fontsize_col       = 10,
    cellwidth          = 30,
    cellheight         = 30
  )


pg_ecoli_astral %>% 
  fromList() %>% 
  upset(nsets = ncol(.),
        order.by = "freq",
        decreasing = TRUE,
        nintersects = 10)



pg_ecoli_lumos <- pg_ecoli %>% 
  { .[str_detect(names(.), "FusionLumos")] } %>% 
   set_names( word(names(.), 3, sep = "/") )


pg_ecoli_lumos %>% 
  jpw() %>% 
  as.matrix() %>% 
  pheatmap(
    cluster_rows       = TRUE,   # or TRUE if you want clustering
    cluster_cols       = TRUE,
    border_color       = NA,
    color              = viridis(100),
    na_col             = "grey90",
    main               = "FusionLumos E coli | Pairwise Jaccard",
    angle_col          = 45,
    fontsize_row       = 10,
    fontsize_col       = 10,
    cellwidth          = 30,
    cellheight         = 30
  )

pg_ecoli_astral %>% 
  fromList() %>% 
  upset(nsets = ncol(.),
        order.by = "freq",
        decreasing = TRUE,
        nintersects = 10)



```




```{r}
sessionInfo()
```






